### ISSUE TITLE
ip address privacy concerns

### ISSUE THREAD

**Issue by fippo** [opentok/rtcstats#19]
@ggarber mentioned there are some concerns exposing and storing ip addresses. I don't think that is a real issue since those addresses are already transmitted via the signaling server (minus any prflx ones) but... storing them might be an issue, especially long-term.

This needs to be removed in any
- c= line in any SDP
- a=rtcp line in any SDP
- a=candidate line in any SDP
- any onicecandidate / addIceCandidate event
- getStats

**Comment by ggarber** [comment]
we should get the country/region before removing IPs

**Comment by fippo** [comment]
which implies server-side removal...

**Comment by ggarber** [comment]
yep, i was assuming that was the idea :)

**Comment by ggarber** [comment]
that way we can log the IPs for NSA if they pay us enough for that

**Comment by fippo** [comment]
well, I filed it here. Let the backend deal with that.
