### ISSUE TITLE
use requestIdleCallback instead of setTimeout

### ISSUE THREAD

**Issue by fippo** [opentok/rtcstats#64]
because its awesome and we don't need high priority (in the backend)
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

might still require a setTimeout to schedule  a new idle callback in the future but...

**Comment by juandebravo** [comment]
I didn't know about this feature, thanks for the tip! 👍

**Comment by fippo** [comment]
not a priority really so closing.
